export const
  SAVE_RAIN = 'SAVE_RAIN',
  SAVE_LATITUDE = 'SAVE_LATITUDE',
  SAVE_LONGITUDE = 'SAVE_LONGITUDE',
  SAVE_DATE = 'SAVE_DATE',
  SAVE_TIME = 'SAVE_TIME',
  SAVE_MINTEMP = 'SAVE_MINTEMP',
  SAVE_MAXTEMP = 'SAVE_MAXTEMP',
  SAVE_DATA = 'SAVE_DATA';
