export const
  SAVE_RAIN = 'SAVE_RAIN',
  SAVE_LATITUDE = 'SAVE_LATITUDE',
  SAVE_LONGITUDE = 'SAVE_LONGITUDE',
  SAVE_TIME = 'SAVE_TIME',
  SAVE_MINTEMP = 'SAVE_MINTEMP',
  SAVE_MAXTEMP = 'SAVE_MAXTEMP',
  SAVE_UNIXTIME = 'SAVE_UNIXTIME',
  SAVE_DATA = 'SAVE_DATA',
  SAVE_RESULT = 'SAVE_RESULT',
  TOGGLE_DRAWER = 'TOGGLE_DRAWER';
